<?php
/**
 * Class UserSeeder.
 *
 * @category Doctry
 *
 * @package Doctry
 * @author  Amentotech <theamentotech@gmail.com>
 * @license http://www.amentotech.com Amentotech
 * @link    http://www.amentotech.com
 */
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

/**
 * Class UserSeeder
 */
class UserSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert(
            [
                //Admin
                [
                    'first_name' => 'chris',
                    'last_name' => 'evans',
                    'slug' => 'chris-evans',
                    'email' => 'admin@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 1,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                //Doctor
                [
                    'first_name' => 'Ava',
                    'last_name' => 'Nguyen',
                    'slug' => 'ava-nguyen',
                    'email' => 'ava@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 1,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => Carbon::now()->addDays(30)->format('Y-m-d H:i:s'),
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                //Hospital
                [
                    'first_name' => 'Willow Green',
                    'last_name' => 'Hospital',
                    'slug' => 'willow-green-hospital',
                    'email' => 'kai@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 4,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                //Regular
                [
                    'first_name' => 'Jhon',
                    'last_name' => 'Xavier',
                    'slug' => 'jhon-xavier',
                    'email' => 'jhon@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 8,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                //Doctors
                [
                    'first_name' => 'Elijah',
                    'last_name' => 'Johnson',
                    'slug' => 'elijah-johnson',
                    'email' => 'johnson@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 2,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => Carbon::now()->addDays(30)->format('Y-m-d H:i:s'),
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'Brooklyn',
                    'last_name' => 'Chan',
                    'slug' => 'brooklyn-chan',
                    'email' => 'chan@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 2,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'Beau',
                    'last_name' => 'Simard',
                    'slug' => 'beau-simard',
                    'email' => 'beau@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 2,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => Carbon::now()->addDays(30)->format('Y-m-d H:i:s'),
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'Isobel',
                    'last_name' => 'Jones',
                    'slug' => 'isobel-jones',
                    'email' => 'isobel@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 3,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'Kian',
                    'last_name' => 'Johnson',
                    'slug' => 'kian-johnson',
                    'email' => 'kian@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 3,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => Carbon::now()->addDays(30)->format('Y-m-d H:i:s'),
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'Sarah',
                    'last_name' => 'Chapman',
                    'slug' => 'sarah-chapman',
                    'email' => 'sarah@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 3,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'Abhinav',
                    'last_name' => 'Balasubramanium',
                    'slug' => 'abhinav-balasubramanium',
                    'email' => 'balasubramanium@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 4,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => Carbon::now()->addDays(30)->format('Y-m-d H:i:s'),
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                //Hospitals
                [
                    'first_name' => 'Summer spring',
                    'last_name' => 'Hospital',
                    'slug' => 'summer-spring-hospital',
                    'email' => 'anika@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 4,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'Care & Cure',
                    'last_name' => 'Hospital',
                    'slug' => 'care-cure-hospital',
                    'email' => 'shreyas@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 4,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => Carbon::now()->addDays(30)->format('Y-m-d H:i:s'),
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'Health Object',
                    'last_name' => 'Hospital',
                    'slug' => 'health-object-hospital',
                    'email' => 'tekin@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 5,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => Carbon::now()->addDays(30)->format('Y-m-d H:i:s'),
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'Another life',
                    'last_name' => 'Hospital',
                    'slug' => 'another-life-hospital',
                    'email' => 'karaca@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 5,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => Carbon::now()->addDays(30)->format('Y-m-d H:i:s'),
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'Velit',
                    'last_name' => 'Şenli',
                    'slug' => 'velit-senli',
                    'email' => 'comak@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 5,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'West valley',
                    'last_name' => 'hospital',
                    'slug' => 'west-valley-hospital',
                    'email' => 'mills@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 6,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => Carbon::now()->addDays(30)->format('Y-m-d H:i:s'),
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'Happy space’s',
                    'last_name' => 'Hospital',
                    'slug' => 'happy-space’s-hospital',
                    'email' => 'dixon@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 6,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => Carbon::now()->addDays(30)->format('Y-m-d H:i:s'),
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'Life',
                    'last_name' => 'Hospital',
                    'slug' => 'life-hospital',
                    'email' => 'coleman@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 6,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => Carbon::now()->addDays(30)->format('Y-m-d H:i:s'),
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'St. Denwer',
                    'last_name' => 'Hospital',
                    'slug' => 'st-denwer-hospital',
                    'email' => 'james@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 7,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                //Regular
                [
                    'first_name' => 'Kai',
                    'last_name' => 'Clarke',
                    'slug' => 'kai-clarke',
                    'email' => 'clarke@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 7,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => Carbon::now()->addDays(30)->format('Y-m-d H:i:s'),
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'Georgia',
                    'last_name' => 'Baker',
                    'slug' => 'georgia-baker',
                    'email' => 'baker@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 7,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => Carbon::now()->addDays(30)->format('Y-m-d H:i:s'),
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'Ralph',
                    'last_name' => 'Davis',
                    'slug' => 'ralph-davis',
                    'email' => 'davis@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 8,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => Carbon::now()->addDays(30)->format('Y-m-d H:i:s'),
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'first_name' => 'Alexa',
                    'last_name' => 'Xavier',
                    'slug' => 'alexa-xavier',
                    'email' => 'alexa@amentotech.com',
                    'password' => bcrypt('google'),
                    'location_id' => 8,
                    'user_verified' => 1,
                    'verification_code' => null,
                    'package_expiry' => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
            ]
        );
    }
}
