version: '3'

services: 
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./development/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks: 
      - application-network

  composer:
    container_name: composer
    image: composer
    command: /bin/bash "/app/commands/production/start-composer.sh"
    volumes: 
      - ./:/app
    networks: 
      - application-network

  npm:
    container_name: npm
    image: node:14.1.0-slim
    command: /bin/bash "/var/www/commands/production/start-npm.sh"
    volumes: 
      - ./:/var/www
    networks: 
      - application-network

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes: 
      - ./:/var/www
      - ./production/nginx/conf.d/:/etc/nginx/conf.d/
    networks: 
      - application-network

  database:
    image: mysql:8.0
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    volumes: 
      - data:/var/lib/mysql
      - ./production/mysql/my.conf:/etc/mysql/my.conf
    networks: 
      - application-network

  redis:
    image: docker.io/bitnami/redis:6.2
        ports:
          - '6379'
        environment:
          # ALLOW_EMPTY_PASSWORD is recommended only for development.
          - ALLOW_EMPTY_PASSWORD=yes
          - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
        command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb  
        volumes:
          - /path/to/redis-persistence:/bitnami/redis/data
        networks: 
          - application-network   

networks: 
  application-network:
    driver: bridge
    
volumes:
  data:
    driver: local
  redis_data:
    driver: local 
