<?php
/**
 * Class UserServiceSeeder
 *
 * @category Doctry
 *
 * @package Doctry
 * @author  Amentotech <theamentotech@gmail.com>
 * @license http://www.amentotech.com Amentotech
 * @link    http://www.amentotech.com
 */
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

/**
 * Class UserServiceSeeder
 */
class UserServiceSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('user_service')->insert(
            [  
                
                [
                    'user_id' => 2,
                    'service_id' => 1,
                    'type' => 'doctor',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 2,
                    'service_id' => 16,
                    'type' => 'doctor',
                    'speciality' => 14,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 2,
                    'service_id' => 11,
                    'type' => 'doctor',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 2,
                    'service_id' => 7,
                    'type' => 'doctor',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 2,
                    'service_id' => 15,
                    'type' => 'doctor',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 2,
                    'service_id' => 9,
                    'type' => 'doctor',
                    'speciality' => 10,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 2,
                    'service_id' => 14,
                    'type' => 'doctor',
                    'speciality' => 10,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 2,
                    'service_id' => 12,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                
                [
                    'user_id' => 2,
                    'service_id' => 14,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 2,
                    'service_id' => 10,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 2,
                    'service_id' => 8,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],

                [
                    'user_id' => 2,
                    'service_id' => 13,
                    'type' => 'doctor',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 2,
                    'service_id' => 4,
                    'type' => 'doctor',
                    'speciality' => 2,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 2,
                    'service_id' => 3,
                    'type' => 'doctor',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 3,
                    'service_id' => 1,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 3,
                    'service_id' => 16,
                    'type' => 'hospital',
                    'speciality' => 14,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 3,
                    'service_id' => 11,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 3,
                    'service_id' => 7,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 3,
                    'service_id' => 15,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 3,
                    'service_id' => 9,
                    'type' => 'hospital',
                    'speciality' => 10,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 3,
                    'service_id' => 14,
                    'type' => 'hospital',
                    'speciality' => 10,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 3,
                    'service_id' => 12,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                
                [
                    'user_id' => 3,
                    'service_id' => 14,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 3,
                    'service_id' => 10,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 3,
                    'service_id' => 8,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],

                [
                    'user_id' => 3,
                    'service_id' => 13,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 3,
                    'service_id' => 4,
                    'type' => 'hospital',
                    'speciality' => 2,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 3,
                    'service_id' => 3,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 5,
                    'service_id' => 1,
                    'type' => 'doctor',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 5,
                    'service_id' => 16,
                    'type' => 'doctor',
                    'speciality' => 14,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 5,
                    'service_id' => 11,
                    'type' => 'doctor',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 5,
                    'service_id' => 7,
                    'type' => 'doctor',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 5,
                    'service_id' => 15,
                    'type' => 'doctor',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 5,
                    'service_id' => 9,
                    'type' => 'doctor',
                    'speciality' => 10,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 5,
                    'service_id' => 14,
                    'type' => 'doctor',
                    'speciality' => 10,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 5,
                    'service_id' => 12,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 5,
                    'service_id' => 14,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 5,
                    'service_id' => 10,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 5,
                    'service_id' => 8,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 5,
                    'service_id' => 13,
                    'type' => 'doctor',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 5,
                    'service_id' => 4,
                    'type' => 'doctor',
                    'speciality' => 2,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 5,
                    'service_id' => 3,
                    'type' => 'doctor',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 6,
                    'service_id' => 1,
                    'type' => 'doctor',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 6,
                    'service_id' => 16,
                    'type' => 'doctor',
                    'speciality' => 14,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 6,
                    'service_id' => 11,
                    'type' => 'doctor',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 6,
                    'service_id' => 7,
                    'type' => 'doctor',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 6,
                    'service_id' => 15,
                    'type' => 'doctor',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 6,
                    'service_id' => 9,
                    'type' => 'doctor',
                    'speciality' => 10,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 6,
                    'service_id' => 14,
                    'type' => 'doctor',
                    'speciality' => 10,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 6,
                    'service_id' => 12,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                
                [
                    'user_id' => 6,
                    'service_id' => 14,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 6,
                    'service_id' => 10,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 6,
                    'service_id' => 8,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],

                [
                    'user_id' => 6,
                    'service_id' => 13,
                    'type' => 'doctor',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 6,
                    'service_id' => 4,
                    'type' => 'doctor',
                    'speciality' => 2,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 6,
                    'service_id' => 3,
                    'type' => 'doctor',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 7,
                    'service_id' => 1,
                    'type' => 'doctor',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 7,
                    'service_id' => 16,
                    'type' => 'doctor',
                    'speciality' => 14,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 7,
                    'service_id' => 11,
                    'type' => 'doctor',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 7,
                    'service_id' => 7,
                    'type' => 'doctor',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 7,
                    'service_id' => 15,
                    'type' => 'doctor',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 7,
                    'service_id' => 9,
                    'type' => 'doctor',
                    'speciality' => 10,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 7,
                    'service_id' => 14,
                    'type' => 'doctor',
                    'speciality' => 10,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 7,
                    'service_id' => 12,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                
                [
                    'user_id' => 7,
                    'service_id' => 14,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 7,
                    'service_id' => 10,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 7,
                    'service_id' => 8,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],

                [
                    'user_id' => 7,
                    'service_id' => 13,
                    'type' => 'doctor',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 7,
                    'service_id' => 4,
                    'type' => 'doctor',
                    'speciality' => 2,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 7,
                    'service_id' => 3,
                    'type' => 'doctor',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 8,
                    'service_id' => 1,
                    'type' => 'doctor',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 8,
                    'service_id' => 16,
                    'type' => 'doctor',
                    'speciality' => 14,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 8,
                    'service_id' => 11,
                    'type' => 'doctor',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 8,
                    'service_id' => 7,
                    'type' => 'doctor',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 8,
                    'service_id' => 15,
                    'type' => 'doctor',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 8,
                    'service_id' => 9,
                    'type' => 'doctor',
                    'speciality' => 10,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 8,
                    'service_id' => 14,
                    'type' => 'doctor',
                    'speciality' => 10,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 8,
                    'service_id' => 12,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                
                [
                    'user_id' => 8,
                    'service_id' => 14,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 8,
                    'service_id' => 10,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 8,
                    'service_id' => 8,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],

                [
                    'user_id' => 8,
                    'service_id' => 13,
                    'type' => 'doctor',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 8,
                    'service_id' => 4,
                    'type' => 'doctor',
                    'speciality' => 2,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 8,
                    'service_id' => 3,
                    'type' => 'doctor',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 9,
                    'service_id' => 15,
                    'type' => 'doctor',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 9,
                    'service_id' => 11,
                    'type' => 'doctor',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 9,
                    'service_id' => 3,
                    'type' => 'doctor',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 9,
                    'service_id' => 1,
                    'type' => 'doctor',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 9,
                    'service_id' => 8,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 9,
                    'service_id' => 13,
                    'type' => 'doctor',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 9,
                    'service_id' => 10,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 9,
                    'service_id' => 12,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 9,
                    'service_id' => 14,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 9,
                    'service_id' => 7,
                    'type' => 'doctor',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 10,
                    'service_id' => 15,
                    'type' => 'doctor',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 10,
                    'service_id' => 11,
                    'type' => 'doctor',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 10,
                    'service_id' => 3,
                    'type' => 'doctor',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 10,
                    'service_id' => 1,
                    'type' => 'doctor',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 10,
                    'service_id' => 8,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 10,
                    'service_id' => 13,
                    'type' => 'doctor',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 10,
                    'service_id' => 10,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 10,
                    'service_id' => 12,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 10,
                    'service_id' => 14,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 10,
                    'service_id' => 7,
                    'type' => 'doctor',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 11,
                    'service_id' => 15,
                    'type' => 'doctor',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 11,
                    'service_id' => 11,
                    'type' => 'doctor',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 11,
                    'service_id' => 3,
                    'type' => 'doctor',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 11,
                    'service_id' => 1,
                    'type' => 'doctor',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 11,
                    'service_id' => 8,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 11,
                    'service_id' => 13,
                    'type' => 'doctor',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 11,
                    'service_id' => 10,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 11,
                    'service_id' => 12,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 11,
                    'service_id' => 14,
                    'type' => 'doctor',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 11,
                    'service_id' => 7,
                    'type' => 'doctor',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                // Hospitals
                [
                    'user_id' => 12,
                    'service_id' => 15,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 12,
                    'service_id' => 11,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 12,
                    'service_id' => 3,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 12,
                    'service_id' => 1,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 12,
                    'service_id' => 8,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 12,
                    'service_id' => 13,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 12,
                    'service_id' => 10,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 12,
                    'service_id' => 12,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 12,
                    'service_id' => 14,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 12,
                    'service_id' => 7,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 13,
                    'service_id' => 15,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 13,
                    'service_id' => 11,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 13,
                    'service_id' => 3,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 13,
                    'service_id' => 1,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 13,
                    'service_id' => 8,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 13,
                    'service_id' => 13,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 13,
                    'service_id' => 10,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 13,
                    'service_id' => 12,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 13,
                    'service_id' => 14,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 13,
                    'service_id' => 7,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 14,
                    'service_id' => 15,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 14,
                    'service_id' => 11,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 14,
                    'service_id' => 3,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 14,
                    'service_id' => 1,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 14,
                    'service_id' => 8,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 14,
                    'service_id' => 13,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 14,
                    'service_id' => 10,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 14,
                    'service_id' => 12,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 14,
                    'service_id' => 14,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 14,
                    'service_id' => 7,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 15,
                    'service_id' => 15,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 15,
                    'service_id' => 11,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 15,
                    'service_id' => 3,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 15,
                    'service_id' => 1,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 15,
                    'service_id' => 8,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 15,
                    'service_id' => 13,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 15,
                    'service_id' => 10,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 15,
                    'service_id' => 12,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 15,
                    'service_id' => 14,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 15,
                    'service_id' => 7,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 16,
                    'service_id' => 15,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 16,
                    'service_id' => 11,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 16,
                    'service_id' => 3,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 16,
                    'service_id' => 1,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 16,
                    'service_id' => 8,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 16,
                    'service_id' => 13,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 16,
                    'service_id' => 10,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 16,
                    'service_id' => 12,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 16,
                    'service_id' => 14,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 16,
                    'service_id' => 7,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 17,
                    'service_id' => 15,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 17,
                    'service_id' => 11,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 17,
                    'service_id' => 3,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 17,
                    'service_id' => 1,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 17,
                    'service_id' => 8,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 17,
                    'service_id' => 13,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 17,
                    'service_id' => 10,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 17,
                    'service_id' => 12,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 17,
                    'service_id' => 14,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 17,
                    'service_id' => 7,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 18,
                    'service_id' => 15,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 18,
                    'service_id' => 11,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 18,
                    'service_id' => 3,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 18,
                    'service_id' => 1,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 18,
                    'service_id' => 8,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 18,
                    'service_id' => 13,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 18,
                    'service_id' => 10,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 18,
                    'service_id' => 12,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 18,
                    'service_id' => 14,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 18,
                    'service_id' => 7,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 19,
                    'service_id' => 15,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 19,
                    'service_id' => 11,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 19,
                    'service_id' => 3,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 19,
                    'service_id' => 1,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 19,
                    'service_id' => 8,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 19,
                    'service_id' => 13,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 19,
                    'service_id' => 10,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 19,
                    'service_id' => 12,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 19,
                    'service_id' => 14,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 19,
                    'service_id' => 7,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 20,
                    'service_id' => 15,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 20,
                    'service_id' => 11,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 20,
                    'service_id' => 3,
                    'type' => 'hospital',
                    'speciality' => 5,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 20,
                    'service_id' => 1,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 20,
                    'service_id' => 8,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 20,
                    'service_id' => 13,
                    'type' => 'hospital',
                    'speciality' => 1,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 20,
                    'service_id' => 10,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 20,
                    'service_id' => 12,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 20,
                    'service_id' => 14,
                    'type' => 'hospital',
                    'speciality' => 4,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'user_id' => 20,
                    'service_id' => 7,
                    'type' => 'hospital',
                    'speciality' => 9,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
            ]
        );
    }
}
